Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 303
      MemorySize: 1664
      Handler: helloworld.App
      CodeUri: /Users/jarotball/Study/java_architect/java_serverless_app_on_aws_2022/helloWorld/HelloWorldFunction
      Runtime: java11
      Architectures:
        - x86_64