server:
  port: 8181
  compression:
    enabled: true
  tomcat:
    connection-timeout:
spring:
  config:
    activate:
      on-profile: dev

---
server:
  port: 8282
spring:
  config:
    activate:
      on-profile: uat
